version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: simtax_app
    restart: unless-stopped
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - php-socket:/var/run/php
    networks:
      - simtax_network

  nginx:
    image: nginx:alpine
    container_name: simtax_nginx
    ports:
      - "8020:80"
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - php-socket:/var/run/php
    networks:
      - simtax_network
    depends_on:
      - app

volumes:
  php-socket:

networks:
  simtax_network:
    driver: bridge
